### ISSUE TITLE
Determine a Policy for Files Larger than 5 GB

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/haiku9#27]
Currently, objects within an S3 bucket must be less than 5GB in size.  If you attempt to upload a bigger file, the AWS SDK automatically splits it into chunks that get stored as separate objects.  This complicates both static website delivery and MD5 integrity checks during S3 sync.

Currently, H9 takes no steps to handle this edge case.  Should we acknowledge that files that large are unlikely to be used and disallow them?  Or should we accommodate them?

**Comment by dyoder** [comment]
For now, let's just assume that isn't going to happen, but leave this ticket open and we'll plan it for a later release.
