### ISSUE TITLE
should environments be a dictionary instead of an array?

### ISSUE THREAD

**Issue by dyoder** [pandastrike/haiku9#44]
The name of environment could be the key. Not a high-priority, just slightly simpler.

**Comment by freeformflow** [comment]
I agree that it looks nicer, but when it comes to schema validation, I defined what `environment` is so you have N environments.  But (and please correct me if I'm wrong) you can't schematize an object with N arbitrary keys, but the values all have to be `environment`.  

If we wanted to limit the user to `feature`, `staging`, and `production` environments, we could accomplish this.  But I erred on the side of end-user flexibility.

**Comment by dyoder** [comment]
[You can define a dictionary-like type](http://json-schema.org/example2.html) using `additionalProperties`.

**Comment by dyoder** [comment]
Well, that example uses `patternProperties`. Having a hard time finding a good example. But basically you can define `additionalProperties` as another nested type.

**Comment by dyoder** [comment]
Okay here's one:

http://stackoverflow.com/questions/27357861/dictionary-like-json-schema/27375654#27375654
