### ISSUE TITLE
SASS/SCSS Support

### ISSUE THREAD

**Issue by benniemosher** [pandastrike/haiku9#53]

**Comment by f1337** [comment]
It looks like we'll need to:

* add a sass/scss helper to [panda-9000/src/helpers.coffee](https://github.com/pandastrike/panda-9000/blob/31123a920152cfe5492ac16cfdd1ff5b2f36659b/src/helpers.coffee)
* add a sass/scss "survey" script to `src/survey` (ala [stylus.coffee](https://github.com/pandastrike/haiku9/blob/master/src/survey/stylus.coffee))
* add the aforementioned "survey" script to [src/survey/index.coffee](https://github.com/pandastrike/haiku9/blob/890d4c8f41ce75e55bbad707c8b58ccc98de4767/src/survey/index.coffee)
