### ISSUE TITLE
Use separate, simple fixture sites for tests

### ISSUE THREAD

**Issue by diminish7** [pandastrike/haiku9#56]
Right now, the `build` test runs against `examples/simple-site`, which includes testing jade, coffeescript and stylus templates all in one test.

First, that makes our tests rely on the example site, so if we change the example site for documentation / quick-start purposes, it may break our tests.

Second, it lumps all building tests into a single build. Does it make sense to have one fixture site to test jade, one to test coffeescript, one to test stylus etc? This doesn't seem like a huge deal right now since those three things cover separate concerns, but if we add a markdown test, and start adding additional asset types, the single simple site will get cluttered and hard to manage.

**Comment by f1337** [comment]
:+1: decouple *all the things*

**Comment by f1337** [comment]
See https://github.com/pandastrike/haiku9/issues/61
