### ISSUE TITLE
Coffeescript "require" support

### ISSUE THREAD

**Issue by f1337** [pandastrike/haiku9#58]
Or some equivalent which supports modular code broken into multiple files, compiling them into a single file during the pipeline build?

**Comment by dyoder** [comment]
We have this via the Browserify asset type. Basically, you put the JS in a directory with a `package.json` identifying modules to load. Example here:

https://github.com/pandastrike/blurb9/tree/master/www/assets/js/_site

**Comment by f1337** [comment]
Verifying we can use the Browserify asset type w/ local files. Will close this issue once confirmed. Thank you @dyoder !

**Comment by f1337** [comment]
Thank you @dyoder! I gave it a go with our panda-music project, and it works: https://github.com/pandastrike/panda-music/pull/15

Closing w/ no add'l work needed.
