### ISSUE TITLE
Fix periodic test failures

### ISSUE THREAD

**Issue by diminish7** [pandastrike/haiku9#69]
About once every 10 test runs, one of the fixture projects fails to build in time for the assertion.

**Comment by dyoder** [comment]
I think this is why I ended up using a synchroization helper instead of forking.

https://github.com/pandastrike/p42/blob/rewrite/test/helpers.coffee#L12-L32

Ex:

https://github.com/pandastrike/p42/blob/rewrite/test/foundation.coffee#L83

**Comment by diminish7** [comment]
@dyoder Cool, thanks for the links! I'm going to try to solve it async first, because it's not making a ton of sense why it is failing right now... But I'll definitely fall back to your sync approach once I have a handle on what's going wrong in the async version. 👍

**Comment by diminish7** [comment]
It's interesting, because the failure is actually happening in a synchronous portion of code. We're waiting on the build child process to finish before checking for the file, but I'm seeing an occasional tiny lag (30ms to 40ms) between the write process finishing and the files actually being present in the file system.

**Comment by dyoder** [comment]
I think it's because the process can return without waiting on the file to exist. That is, if you don't block in the child on the file write, it will exit because there's effectively no callback that Node needs to run.

**Comment by dyoder** [comment]
Also I'm not 100% certain that the process exit event doesn't introduce additional timing issues. I don't know precisely when that is triggered.

**Comment by dyoder** [comment]
If I read the code right, the problem is that the last part of the reactive flow for `build` does the save. If that returns a promise (which it probably does, but I'd have to check), the flow isn't waiting on that promise because it's the last thing in the flow.

**Comment by dyoder** [comment]
That is, `build` waits on the flow, but the flow itself (the `go` function) isn't waiting on the last promise from `write`. To fix that, I think we could just add a `pull` at the end there (which “pulls” promises from the flow into values once they resolve).

**Comment by diminish7** [comment]
Using `pull` didn't do it. I wonder if you are right about `child_process`'s `exit` event causing the timing issue? I could possibly fix that by scrapping the child process stuff, and doing a synchronous approach. I'll play around with that as I have time, but for now, I'm pushing a solution that just polls for the files until they exist.
