### ISSUE TITLE
Make auto-build the default

### ISSUE THREAD

**Issue by dyoder** [pandastrike/haiku9#74]
The biggest problem I've had over time is forgetting to run `build` before `publish`. My guess is 99% of time, people want what they publish to reflect what's in their content directory. So we should just do that automatically, make `publish` depend on `build`. If that's really an issue somehow, we can make it an config preference.

**Comment by freeformflow** [comment]
This has gained new interest this morning, so I'm bumping and linking it to a counterpart in Panda Sky.  The advantage is that it allows you to tinker more manually before pushing stuff to the Cloud.  That was all good in the earliest stages of development, but less so now.  Dan has a ticket in H9 to the effect of auto-builds.  I think that we should retain something like a `--nobuild` flag, but make build the default.

**Comment by dyoder** [comment]
Also, if you haven't built, and there's no build directory, we should gracefully detect that. Auto-build would make this go away, but if we have `--nobuild` than we'd still need to check for it.
