### ISSUE TITLE
Implement caching compiled functions

### ISSUE THREAD

**Issue by maheshyellai** [pandastrike/haiku9#9]
Even though Jade implements [caching](https://github.com/jadejs/jade/blob/master/lib/index.js#L166-176), its simplistic. haiku9 should implement LRU caching of compiled functions.

**Comment by dyoder** [comment]
Doesn't really even need to be LRU, since it's pretty unlikely there'd be so many templates that we'd run out of memory keeping the compiled versions.

**Comment by maheshyellai** [comment]
Ok, closing this as we can simply use Jade's caching for now.
